-- Polly's Pop — Database Schema
-- Write all CREATE TABLE statements below in dependency order.
--
-- 1. brands
-- 2. products          (UPC codes: reference data only, never generated)
-- 3. production_batches (format: DDMM + sequence, e.g. 2606111)
-- 4. pallets            (system-generated barcode: flavor + date + pallet number)
-- 5. inventory_movements (every state/location change writes a row)
-- 6. sold_products      (feeds analytics CSV export)
-- 7. notifications      (expiration alert at 3 months; flavor-order placeholder Phase 2)
--
-- Business rules to enforce in constraints/application logic:
--   - Bottle batch number: BBxxx (3-digit sequential, never resets daily)
--   - Locations: Production Floor, Warehouse 1, Warehouse 2
--   - Expiration date: manually entered at bottling time
--   - Only pallet-level barcodes are generated by this system

CREATE TABLE brands (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);